Repository etclabscore/jade-desktop, pull requests merged in 2019-10, with the labels that each got.

#56 fix: update jade service runner to 1.7.0
  package-lock.json
  package.json
Labels: enhancement

#61 fix: add service summaries
  package-lock.json
  package.json
  src/App.tsx
Labels: enhancement

#67 fix: update jade service runner to 1.7.4
  package-lock.json
  package.json
Labels: bug

#76 fix: restructued readme content, this fixes #60
  README.md
Labels: documentation

#79 fix: change RUN IT img to link to release, fixes #78
  README.md
Labels: documentation
